FROM python:3.12-slim

WORKDIR /app
COPY pydep/ .

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y ca-certificates
RUN update-ca-certificates

RUN pip install --no-cache-dir -r requirements_ocr.txt

RUN python -c "import easyocr; easyocr.Reader(['en'], recog_network='english_g2');print('easyocr model downloaded')"