FROM python:3.12-slim

WORKDIR /app
COPY pydep/ .

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libcairo2 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libgdk-pixbuf-2.0-0 \
    libffi-dev \
    shared-mime-info \
    g++ \
    pkg-config \
    libopencv-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*
ENV LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH

RUN pip install --no-cache-dir -r requirements_pymodule.txt
RUN pip install pybind11
RUN g++ -O3 -Wall -shared -std=c++14 -fPIC \
    $(python3.12-config --includes) \
    -I$(python3.12 -m pybind11 --includes | cut -c3-) \
    $(pkg-config --cflags opencv4) \
    -o customFloodFill$(python3.12-config --extension-suffix) app.cpp \
    $(python3.12-config --ldflags) \
    $(pkg-config --libs opencv4) -I include

RUN g++ -O3 -Wall -shared -std=c++14 -fPIC \
    $(python3.12-config --includes) \
    -I$(python3.12 -m pybind11 --includes | cut -c3-) \
    $(pkg-config --cflags opencv4) \
    -o flipMatch$(python3.12-config --extension-suffix) flip.cpp \
    $(python3.12-config --ldflags) \
    $(pkg-config --libs opencv4) -I include

RUN apt-get update && apt-get install -y ca-certificates
RUN update-ca-certificates

RUN mkdir -p pdfTemp inputs outputs


