FROM golang:1.23-bookworm AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main .

FROM debian:bookworm-slim

WORKDIR /app
COPY --from=builder /app/main .

RUN mkdir -p pdfTemp inputs outputs
RUN apt-get update && apt-get install -y ca-certificates
RUN update-ca-certificates
